// Setup and configuration wizard for the Trading Bot

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

function question(prompt) {
    return new Promise((resolve) => {
        rl.question(prompt, resolve);
    });
}

async function setupBot() {
    console.log('🤖 Welcome to the Trading Bot Setup Wizard!\n');
    
    console.log('This wizard will help you configure your trading bot.');
    console.log('You can always edit the .env file manually later.\n');

    const config = {};

    // Check if .env already exists
    const envPath = path.join(__dirname, '..', '.env');
    const envExists = fs.existsSync(envPath);
    
    if (envExists) {
        const overwrite = await question('⚠️  .env file already exists. Overwrite? (y/N): ');
        if (overwrite.toLowerCase() !== 'y') {
            console.log('Setup cancelled. Edit .env manually if needed.');
            rl.close();
            return;
        }
    }

    console.log('\n📱 Telegram Bot Configuration');
    console.log('To create a bot, message @BotFather on Telegram and use /newbot\n');
    
    config.TELEGRAM_BOT_TOKEN = await question('Enter your Telegram bot token: ');
    
    const allowedChats = await question('Enter allowed chat IDs (comma-separated, or press Enter for all chats): ');
    if (allowedChats.trim()) {
        config.TELEGRAM_ALLOWED_CHATS = allowedChats.trim();
    }

    console.log('\n🧠 OpenAI Configuration');
    console.log('Get your API key from https://platform.openai.com/api-keys\n');
    
    config.OPENAI_API_KEY = await question('Enter your OpenAI API key: ');
    
    const model = await question('OpenAI model (default: gpt-4): ');
    if (model.trim()) {
        config.OPENAI_MODEL = model.trim();
    }

    console.log('\n💹 Delta Exchange Configuration');
    console.log('For live trading, get API keys from https://www.delta.exchange/app/api-management\n');
    
    const paperTrade = await question('Enable paper trading? (Y/n): ');
    config.PAPER_TRADE = paperTrade.toLowerCase() !== 'n';
    
    if (!config.PAPER_TRADE) {
        console.log('⚠️  Live trading enabled. You will need Delta Exchange API credentials.\n');
        config.DELTA_API_KEY = await question('Enter Delta Exchange API key: ');
        config.DELTA_API_SECRET = await question('Enter Delta Exchange API secret: ');
        
        const testnet = await question('Use testnet? (Y/n): ');
        config.DELTA_TESTNET = testnet.toLowerCase() !== 'n';
    }

    console.log('\n⚙️ Trading Configuration');
    
    const riskPercentage = await question('Default risk percentage per trade (default: 2): ');
    if (riskPercentage.trim()) {
        config.DEFAULT_RISK_PERCENTAGE = parseFloat(riskPercentage);
    }
    
    const maxPositions = await question('Maximum concurrent positions (default: 5): ');
    if (maxPositions.trim()) {
        config.MAX_POSITIONS = parseInt(maxPositions);
    }

    console.log('\n🌐 Server Configuration');
    
    const port = await question('Web server port (default: 3000): ');
    if (port.trim()) {
        config.PORT = parseInt(port);
    }
    
    const logLevel = await question('Log level (info/debug/warn/error, default: info): ');
    if (logLevel.trim()) {
        config.LOG_LEVEL = logLevel.trim();
    }

    // Generate .env file
    console.log('\n📝 Generating .env file...');
    
    let envContent = '# Trading Bot Configuration\n';
    envContent += '# Generated by setup wizard\n\n';
    
    envContent += '# Telegram Configuration\n';
    envContent += `TELEGRAM_BOT_TOKEN=${config.TELEGRAM_BOT_TOKEN}\n`;
    if (config.TELEGRAM_ALLOWED_CHATS) {
        envContent += `TELEGRAM_ALLOWED_CHATS=${config.TELEGRAM_ALLOWED_CHATS}\n`;
    }
    envContent += '\n';
    
    envContent += '# OpenAI Configuration\n';
    envContent += `OPENAI_API_KEY=${config.OPENAI_API_KEY}\n`;
    envContent += `OPENAI_MODEL=${config.OPENAI_MODEL || 'gpt-4'}\n`;
    envContent += 'OPENAI_MAX_TOKENS=1000\n\n';
    
    envContent += '# Delta Exchange Configuration\n';
    if (config.DELTA_API_KEY) {
        envContent += `DELTA_API_KEY=${config.DELTA_API_KEY}\n`;
    }
    if (config.DELTA_API_SECRET) {
        envContent += `DELTA_API_SECRET=${config.DELTA_API_SECRET}\n`;
    }
    envContent += 'DELTA_BASE_URL=https://api.delta.exchange\n';
    envContent += `DELTA_TESTNET=${config.DELTA_TESTNET !== false}\n`;
    envContent += `PAPER_TRADE=${config.PAPER_TRADE !== false}\n\n`;
    
    envContent += '# Trading Configuration\n';
    envContent += `DEFAULT_RISK_PERCENTAGE=${config.DEFAULT_RISK_PERCENTAGE || 2}\n`;
    envContent += `MAX_POSITIONS=${config.MAX_POSITIONS || 5}\n`;
    envContent += 'DEFAULT_LEVERAGE=1\n\n';
    
    envContent += '# Database Configuration\n';
    envContent += 'DB_PATH=./data/trading.db\n\n';
    
    envContent += '# Server Configuration\n';
    envContent += `PORT=${config.PORT || 3000}\n`;
    envContent += 'HOST=localhost\n\n';
    
    envContent += '# Logging Configuration\n';
    envContent += `LOG_LEVEL=${config.LOG_LEVEL || 'info'}\n`;
    envContent += 'LOG_FILE=./data/app.log\n\n';
    
    envContent += '# Environment\n';
    envContent += 'NODE_ENV=development\n';

    // Write .env file
    fs.writeFileSync(envPath, envContent);
    
    // Ensure data directory exists
    const dataDir = path.join(__dirname, '..', 'data');
    if (!fs.existsSync(dataDir)) {
        fs.mkdirSync(dataDir, { recursive: true });
    }

    console.log('\n✅ Setup completed successfully!');
    console.log('\n📋 Next steps:');
    console.log('1. Review the generated .env file');
    console.log('2. Add your bot to Telegram groups you want to monitor');
    console.log('3. Start the bot with: npm start');
    console.log('4. Open the dashboard at: http://localhost:' + (config.PORT || 3000));
    console.log('\n⚠️  Important: Start with paper trading to test the system!');
    
    if (config.PAPER_TRADE !== false) {
        console.log('\n✅ Paper trading is enabled - you can test without risk!');
    } else {
        console.log('\n⚠️  Live trading is enabled - please test thoroughly first!');
    }

    rl.close();
}

setupBot().catch(error => {
    console.error('Setup failed:', error);
    rl.close();
    process.exit(1);
});